source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '7.0'

target 'StringScoreDemo' do
  pod 'StringScore_Swift', :path => '../'
end

target 'StringScoreTests' do
  pod 'StringScore_Swift', :path => '../'

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '7.0'
		end
	end
end